In [2]:
import pandas as pd

In [10]:
df_vendas= pd.read_csv('vendas.csv')
df_estoque= pd.read_csv('estoque.csv')
mesclado= df_vendas.merge(df_estoque, on='ref')

# display(df_vendas)
# display(df_estoque)

mesclado= mesclado.rename(columns= {'quantidade' : 'quantidade vendida'})
mesclado= mesclado.rename(columns= {'quantidade_pecas' : 'quantidade em estoque'})

display(mesclado)

,id,ref,number,quantidade vendida,venda,data_venda,tipo_peca_x,idcontrole,tamanho,quantidade em estoque,valor,tipo_peca_y
0,104,1111,42,5,venda,18/12/2023,Vestido Curto,82,42,50,139.9,Vestido Curto
1,104,1111,42,5,venda,18/12/2023,Vestido Curto,83,44,50,139.9,Vestido Curto
2,104,1111,42,5,venda,18/12/2023,Vestido Curto,84,46,50,139.9,Vestido Curto
3,104,1111,42,5,venda,18/12/2023,Vestido Curto,85,48,50,139.9,Vestido Curto
4,104,1111,42,5,venda,18/12/2023,Vestido Curto,86,58,50,139.9,Vestido Curto
...,...,...,...,...,...,...,...,...,...,...,...,...
113,121,4111,62,6,venda,19/12/2023,Vestido Curto,102,52,10,139.9,Vestido Curto
114,121,4111,62,6,venda,19/12/2023,Vestido Curto,103,46,10,139.9,Vestido Curto
115,121,4111,62,6,venda,19/12/2023,Vestido Curto,104,42,10,139.9,Vestido Curto
116,121,4111,62,6,venda,19/12/2023,Vestido Curto,105,58,10,139.9,Vestido Curto
117,121,4111,62,6,venda,19/12/2023,Vestido Curto,106,62,20,139.9,Vestido Curto